services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-backend
    ports:
      - "${API_PORT_MAP:-1234}:8000"
    environment:
      - MONGO_URI=${MONGO_URI:-mongodb://mongodb:27017/}
      - MONGO_USERNAME=${MONGO_USERNAME:-admin}
      - MONGO_PASSWORD=${MONGO_PASSWORD:-secret}
      - MONGO_DATABASE=${MONGO_DATABASE:-url_shortener}
      - MONGO_COLLECTION=${MONGO_COLLECTION:-urls}

      - API_HOST=${API_HOST:-0.0.0.0}
      - API_PORT=8000

      - REDIS_HOST=redis

      - RELOAD_ON_CHANGE=${RELOAD_ON_CHANGE:-false}
    depends_on:
      - mongodb
      - redis
    restart: always

  mongodb:
    image: mongo:8
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-secret}
    volumes:
      - ./db:/data/db
    restart: always

  redis:
    image: redis:8
    container_name: redis
    restart: always